### ISSUE TITLE
[project 2 kaggle] 권한 관련 문의드립니다.

### ISSUE THREAD

**Issue by Yujin-Yujin** [kingsj0405/example-code#3]
안녕하세요.

kaggle에서 test dataset을 download 하려고 하는데, 아래와 같은 메세지가 뜨면서 되지 않습니다.

[!] Unable to perform operation since you're not a participant of this limited competition.
[i] This is a limited-participation competition. Only invited users may participate.

제가 별도로 권한을 신청해야하는 것이 있을까요?
확인 부탁드리겠습니다.

감사합니다!

**Comment by kingsj0405** [comment]
링크가 업데이트 되었습니다!

[LearnUs](https://www.learnus.org/mod/ubboard/article.php?id=2322011&bwid=463745)를 참조해주시기 바랍니다.

감사합니다.

**Comment by Yujin-Yujin** [comment]
https://www.kaggle.com/c/yonsei-csi6702-2021fall-project2

이 링크로 접속하였을 때 발생하였습니다.

혹시 다른 링크가 있을까요?

**Comment by kingsj0405** [comment]
@Yujin-Yujin 아... 새로 올라온 링크도 잘못 올라온 것 같네요. 확인해보겠습니다!

**Comment by kingsj0405** [comment]
@Yujin-Yujin 다시 링크가 업데이트되었습니다. 확인해주시기 바랍니다.

**Comment by Yujin-Yujin** [comment]
감사합니다 :)
